package startFromWSDL.StudentService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 3.3.6
 * 2020-06-05T17:34:15.958+08:00
 * Generated source version: 3.3.6
 */
@WebService(targetNamespace = "http://jw.nju.edu.cn/wsdl", name = "DeleteStudentInterface")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface DeleteStudentInterface {

    @WebMethod
    @WebResult(name = "ifSuccess", targetNamespace = "http://jw.nju.edu.cn/schema", partName = "parameters")
    public java.lang.String opDeleteStudent(

            @WebParam(partName = "parameters", name = "studentNumber", targetNamespace = "http://jw.nju.edu.cn/schema")
                    java.lang.String parameters
    ) throws InvalidDataFault;
}
