package startFromWSDL.StudentService;

import startFromWSDL.ServiceBasis;
import startFromWSDL.types.学生信息类型;
import startFromWSDL.types.学生列表类型;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.3.6
 * 2020-06-05T16:48:37.639+08:00
 * Generated source version: 3.3.6
 */

@javax.jws.WebService(
        serviceName = "StudentService",
        portName = "GetStudentServicePort",
        targetNamespace = "http://jw.nju.edu.cn/wsdl",
        wsdlLocation = "file:/D:/programe/Java/SOA/Assignment10/resources/xml/startFromWSDL/StudentService.wsdl",
        endpointInterface = "startFromWSDL.StudentService.GetStudentInterface")

public class GetStudentServicePortImpl extends ServiceBasis implements GetStudentInterface {

    private static final Logger LOG = Logger.getLogger(GetStudentServicePortImpl.class.getName());

    public GetStudentServicePortImpl() {
        super(null);
    }

    public GetStudentServicePortImpl(学生列表类型 studentList) {
        super(studentList);
    }

    /* (non-Javadoc)
     * @see startFromWSDL.StudentService.GetStudentInterface#opGetStudent(java.lang.String parameters)*
     */
    public 学生信息类型 opGetStudent(String parameters) throws InvalidDataFault {
        LOG.info("Executing operation opGetStudent");
        for (学生信息类型 student : studentList.get学生()) {
            if (student.get学号().equals(parameters)) {
                return student;
            }
        }
        throw new InvalidDataFault("不存在学号为" + parameters + "的学生");
    }

}
