
package startFromWSDL.StudentService;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.3.6
 * 2020-06-05T17:34:15.922+08:00
 * Generated source version: 3.3.6
 */

@WebFault(name = "invalidDataError", targetNamespace = "http://jw.nju.edu.cn/schema")
public class InvalidDataFault extends Exception {

    private java.lang.String invalidDataError;

    public InvalidDataFault() {
        super();
    }

    public InvalidDataFault(String message) {
        super(message);
    }

    public InvalidDataFault(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public InvalidDataFault(String message, java.lang.String invalidDataError) {
        super(message);
        this.invalidDataError = invalidDataError;
    }

    public InvalidDataFault(String message, java.lang.String invalidDataError, java.lang.Throwable cause) {
        super(message, cause);
        this.invalidDataError = invalidDataError;
    }

    public java.lang.String getFaultInfo() {
        return this.invalidDataError;
    }
}
