package startFromWSDL.StudentService;

import startFromWSDL.types.学生信息类型;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 3.3.6
 * 2020-06-05T17:34:15.988+08:00
 * Generated source version: 3.3.6
 *
 */
@WebService(targetNamespace = "http://jw.nju.edu.cn/wsdl", name = "UpdateStudentInterface")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface UpdateStudentInterface {

    @WebMethod
    @WebResult(name = "studentInfo", targetNamespace = "http://jw.nju.edu.cn/schema", partName = "parameters")
    public 学生信息类型 opUpdateStudent(

        @WebParam(partName = "parameters", name = "simplifiedStudentInfo", targetNamespace = "http://jw.nju.edu.cn/schema")
        SimplifiedStudentInfo parameters
    ) throws InvalidDataFault;
}
