
package startFromWSDL.StudentService;

import startFromWSDL.types.学生列表类型;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.3.6
 * 2020-06-05T17:34:16.007+08:00
 * Generated source version: 3.3.6
 *
 */

public class UpdateStudentInterface_UpdateStudentServicePort_Server{

    public UpdateStudentInterface_UpdateStudentServicePort_Server(学生列表类型 studentList) {
        System.out.println("Starting " + getClass().getName());
        Object implementor = new UpdateStudentServicePortImpl(studentList);
        String address = "http://localhost:8080/student/update";
        Endpoint.publish(address, implementor);
    }

}
