
package client.score;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebServiceClient(name = "ScoreService", targetNamespace = "http://jw.nju.edu.cn/wsdl", wsdlLocation = "xml/ScoreService.wsdl")
public class ScoreService
        extends Service {

    private final static URL SCORESERVICE_WSDL_LOCATION;
    private final static WebServiceException SCORESERVICE_EXCEPTION;
    private final static QName SCORESERVICE_QNAME = new QName("http://jw.nju.edu.cn/wsdl", "ScoreService");

    static {
        URL url = null;
        WebServiceException e = null;
        url = ScoreService.class.getResource("/xml/ScoreService.wsdl");
        SCORESERVICE_WSDL_LOCATION = url;
        SCORESERVICE_EXCEPTION = e;
    }

    public ScoreService() {
        super(__getWsdlLocation(), SCORESERVICE_QNAME);
    }

    public ScoreService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SCORESERVICE_QNAME, features);
    }

    public ScoreService(URL wsdlLocation) {
        super(wsdlLocation, SCORESERVICE_QNAME);
    }

    public ScoreService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SCORESERVICE_QNAME, features);
    }

    public ScoreService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ScoreService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * @return returns GetScoreInterface
     */
    @WebEndpoint(name = "GetScoreServicePort")
    public GetScoreInterface getGetScoreServicePort() {
        return super.getPort(new QName("http://jw.nju.edu.cn/wsdl", "GetScoreServicePort"), GetScoreInterface.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns GetScoreInterface
     */
    @WebEndpoint(name = "GetScoreServicePort")
    public GetScoreInterface getGetScoreServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://jw.nju.edu.cn/wsdl", "GetScoreServicePort"), GetScoreInterface.class, features);
    }

    /**
     * @return returns UpdateScoreInterface
     */
    @WebEndpoint(name = "UpdateScoreServicePort")
    public UpdateScoreInterface getUpdateScoreServicePort() {
        return super.getPort(new QName("http://jw.nju.edu.cn/wsdl", "UpdateScoreServicePort"), UpdateScoreInterface.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns UpdateScoreInterface
     */
    @WebEndpoint(name = "UpdateScoreServicePort")
    public UpdateScoreInterface getUpdateScoreServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://jw.nju.edu.cn/wsdl", "UpdateScoreServicePort"), UpdateScoreInterface.class, features);
    }

    /**
     * @return returns DeleteScoreInterface
     */
    @WebEndpoint(name = "DeleteScoreServicePort")
    public DeleteScoreInterface getDeleteScoreServicePort() {
        return super.getPort(new QName("http://jw.nju.edu.cn/wsdl", "DeleteScoreServicePort"), DeleteScoreInterface.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns DeleteScoreInterface
     */
    @WebEndpoint(name = "DeleteScoreServicePort")
    public DeleteScoreInterface getDeleteScoreServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://jw.nju.edu.cn/wsdl", "DeleteScoreServicePort"), DeleteScoreInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SCORESERVICE_EXCEPTION != null) {
            throw SCORESERVICE_EXCEPTION;
        }
        return SCORESERVICE_WSDL_LOCATION;
    }

}
