
package client.score;

import client.InvalidDataFault;
import entity.课程成绩列表类型;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UpdateScoreInterface", targetNamespace = "http://jw.nju.edu.cn/wsdl")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ScoreObjectFactory.class
})
public interface UpdateScoreInterface {


    /**
     * 
     * @param parameters
     * @throws InvalidDataFault
     */
    @WebMethod
    public void opUpdateScore(
        @WebParam(name = "课程成绩列表", targetNamespace = "http://jw.nju.edu.cn/schema", mode = WebParam.Mode.INOUT, partName = "parameters")
        Holder<课程成绩列表类型> parameters)
        throws InvalidDataFault
    ;

}
