
package startFromWSDL.ScoreService;

import startFromWSDL.types.学生列表类型;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.3.6
 * 2020-06-05T12:26:44.040+08:00
 * Generated source version: 3.3.6
 */

public class DeleteScoreInterface_DeleteScoreServicePort_Server {

    public DeleteScoreInterface_DeleteScoreServicePort_Server(学生列表类型 studentList) {
        System.out.println("Starting " + getClass().getName());
        Object implementor = new DeleteScoreServicePortImpl(studentList);
        String address = "http://localhost:8080/score/delete";
        Endpoint.publish(address, implementor);
    }

}
