
package startFromWSDL.ScoreService;

import startFromWSDL.types.学生列表类型;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.3.6
 * 2020-06-05T12:26:44.040+08:00
 * Generated source version: 3.3.6
 *
 */

public class GetScoreInterface_GetScoreServicePort_Server{

    public GetScoreInterface_GetScoreServicePort_Server(学生列表类型 studentList) {
        System.out.println("Starting " + getClass().getName());
        Object implementor = new GetScoreServicePortImpl(studentList);
        String address = "http://localhost:8080/score/get";
        Endpoint.publish(address, implementor);
    }

}
