package startFromWSDL.ScoreService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.6
 * 2020-06-05T12:26:44.056+08:00
 * Generated source version: 3.3.6
 *
 */
@WebServiceClient(name = "ScoreService",
                  wsdlLocation = "file:/D:/programe/Java/SOA/Assignment10/web/xml/startFromWSDL/ScoreService.wsdl",
                  targetNamespace = "http://jw.nju.edu.cn/wsdl")
public class ScoreService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://jw.nju.edu.cn/wsdl", "ScoreService");
    public final static QName UpdateScoreServicePort = new QName("http://jw.nju.edu.cn/wsdl", "UpdateScoreServicePort");
    public final static QName GetScoreServicePort = new QName("http://jw.nju.edu.cn/wsdl", "GetScoreServicePort");
    public final static QName DeleteScoreServicePort = new QName("http://jw.nju.edu.cn/wsdl", "DeleteScoreServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/programe/Java/SOA/Assignment10/web/xml/startFromWSDL/ScoreService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ScoreService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/D:/programe/Java/SOA/Assignment10/web/xml/startFromWSDL/ScoreService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ScoreService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ScoreService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ScoreService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ScoreService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ScoreService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ScoreService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns UpdateScoreInterface
     */
    @WebEndpoint(name = "UpdateScoreServicePort")
    public UpdateScoreInterface getUpdateScoreServicePort() {
        return super.getPort(UpdateScoreServicePort, UpdateScoreInterface.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UpdateScoreInterface
     */
    @WebEndpoint(name = "UpdateScoreServicePort")
    public UpdateScoreInterface getUpdateScoreServicePort(WebServiceFeature... features) {
        return super.getPort(UpdateScoreServicePort, UpdateScoreInterface.class, features);
    }


    /**
     *
     * @return
     *     returns GetScoreInterface
     */
    @WebEndpoint(name = "GetScoreServicePort")
    public GetScoreInterface getGetScoreServicePort() {
        return super.getPort(GetScoreServicePort, GetScoreInterface.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetScoreInterface
     */
    @WebEndpoint(name = "GetScoreServicePort")
    public GetScoreInterface getGetScoreServicePort(WebServiceFeature... features) {
        return super.getPort(GetScoreServicePort, GetScoreInterface.class, features);
    }


    /**
     *
     * @return
     *     returns DeleteScoreInterface
     */
    @WebEndpoint(name = "DeleteScoreServicePort")
    public DeleteScoreInterface getDeleteScoreServicePort() {
        return super.getPort(DeleteScoreServicePort, DeleteScoreInterface.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DeleteScoreInterface
     */
    @WebEndpoint(name = "DeleteScoreServicePort")
    public DeleteScoreInterface getDeleteScoreServicePort(WebServiceFeature... features) {
        return super.getPort(DeleteScoreServicePort, DeleteScoreInterface.class, features);
    }

}
